# Matrix Decomposition

Matrix decomposition is a fundamental concept in linear algebra that breaks down a matrix into simpler components. These components often reveal important properties of the original matrix, making it easier to solve systems of equations, analyze data, or perform numerical computations.

In this notebook, we’ll explore key types of matrix decompositions:

- **Eigen Decomposition and Diagonalizability**
- **Singular Value Decomposition (SVD)**
- **Cholesky Decomposition**

## 1. Eigen Decomposition and Diagonalizability

### Definition of Diagonalizability

A square matrix $( A \in \mathbb{R}^{n \times n} )$ is said to be diagonalizable if it is similar to a diagonal matrix. Mathematically, this means there exists an invertible matrix ($ P \in \mathbb{R}^{n \times n} )$ such that:

$$ D = P^{-1} A P $$

where \( D \) is a diagonal matrix.

This transformation expresses the same linear mapping but in another basis, which consists of the eigenvectors of \( A \).



Let \( A \in \mathbb{R}^{n \times n} \), and let \( \lambda_1, \dots, \lambda_n \) be the eigenvalues with corresponding eigenvectors \( p_1, \dots, p_n \). Define:

$$ P = [p_1, \dots, p_n] $$
$$ D = \text{diag}(\lambda_1, \dots, \lambda_n) $$

Then,

$$ A P = P D $$

which implies:

$$ A p_i = \lambda_i p_i, \quad i = 1, \dots, n $$

### Conditions for Diagonalizability

For \( P \) to be invertible (and hence \( A \) to be diagonalizable), the eigenvectors \( p_1, \dots, p_n \) must form a basis of \( \mathbb{R}^n \). This requires \( A \) to have \( n \) linearly independent eigenvectors.

#### **Theorem: Symmetric Matrices are Always Diagonalizable**

A symmetric matrix \$( S \in \mathbb{R}^{n \times n} \)$ can always be diagonalized. Moreover, the spectral theorem guarantees that we can find an orthonormal basis of eigenvectors. In this case, \( P \) becomes an orthogonal matrix, and the diagonalization simplifies to:

$$ D = P^T A P $$

### Geometric Intuition for Eigen Decomposition

Eigen decomposition of a matrix \( A \) can be interpreted geometrically:

- $( P^{-1} )$ performs a basis change to the eigenbasis.
- $( D )$ scales vectors along the eigenbasis by the eigenvalues \( \lambda_i \).
- $( P)$ transforms these scaled vectors back into the standard coordinate system.

This process is useful for computing powers of \( A \):

$$ A^k = (P D P^{-1})^k = P D^k P^{-1} $$

Since \( D \) is diagonal, computing \( D^k \) involves simply raising each diagonal element to the power \( k \).

#### Determinant via Eigen Decomposition

If \( A = P D P^{-1} \), then:

$$ \det(A) = \det(P D P^{-1}) = \det(D) $$

where:

$$ \det(A) = \prod_{i=1}^{n} \lambda_i $$

---

## 2. Singular Value Decomposition (SVD)

### Definition of SVD

The Singular Value Decomposition (SVD) decomposes any matrix $(A \in \mathbb{R}^{m \times n})$  as:

$$ A = U (\Sigma) V^T $$


where:

- $( U \in \mathbb{R}^{m \times m} ) $is an orthogonal matrix $(( U^T U = I )).$
- $( \Sigma \in \mathbb{R}^{m \times n} )$ is a diagonal matrix with non-negative singular values.
- $( V \in \mathbb{R}^{n \times n} )$ is an orthogonal matrix $(( V^T V = I )).$

### Geometric Intuition for SVD

SVD can be interpreted as a sequence of three transformations:

1. **Basis Change in Domain:** $ V^T $transforms vectors into a new basis.
2. **Scaling:** $ ( \Sigma )$ scales the transformed coordinates.
3. **Basis Change in Codomain:** $( U )$ maps the scaled coordinates into the output space.

### Comparison with Eigen Decomposition

| Property | Eigen Decomposition | Singular Value Decomposition |
|----------|--------------------|-----------------------------|
| Applicability | Only for square matrices | Works for any \( m \times n \) matrix |
| Basis Vectors | Eigenvectors may not be orthogonal | Left and right singular vectors are orthonormal |
| Transformation | Operates within the same vector space | Links domain and codomain via \( \Sigma \) |

### Applications of SVD

- **Dimensionality Reduction:** Truncate small singular values to reduce matrix rank.
- **Image Compression:** Retain only the largest singular values.
- **Least Squares Problems:** Solve overdetermined systems using the pseudoinverse.

---

## 3. Cholesky Decomposition

### What is Cholesky Decomposition?

Cholesky decomposition factors a symmetric positive-definite matrix \( A \) into the product of a lower triangular matrix \( L \) and its transpose:

$$ A = L L^T $$

where \( L \) is a lower triangular matrix with positive diagonal entries.

### When is it Used?

- **Solving linear systems efficiently**
- **Simulating multivariate normal distributions**
- **Optimizing quadratic forms in optimization problems**

### Mathematical Formulation

For a symmetric positive-definite matrix \( A \), Cholesky decomposition is computed as follows:

#### **Compute diagonal elements of \( L \):**

$$ L_{ii} = \sqrt{A_{ii} - \sum_{k=1}^{i-1} L_{ik}^2} $$

#### **Compute off-diagonal elements of \( L \):**

$$ L_{ij} = \frac{1}{L_{jj}} \left(A_{ij} - \sum_{k=1}^{j-1} L_{ik} L_{jk} \right), \quad j < i $$

### Example

Let’s decompose the symmetric positive-definite matrix:

$$ A = \begin{bmatrix} 4 & 12 & -16 \\ 12 & 37 & -43 \\ -16 & -43 & 98 \end{bmatrix} $$

Using Cholesky decomposition, we find:

$$ L = \begin{bmatrix} 2 & 0 & 0 \\ 6 & 1 & 0 \\ -8 & 5 & 3 \end{bmatrix} $$

Cholesky decomposition is computationally efficient and widely used in numerical methods for solving linear systems.

### **Summary of Decompositions**
| Decomposition  | Matrix Type | Form | Used For |
|---------------|------------|------|---------|
| **Eigen Decomposition** | Square matrices with \( n \) independent eigenvectors | \( A = P D P^{-1} \) | Diagonalization, power computations, PCA |
| **SVD** | Any matrix \( A \in \mathbb{R}^{m \times n} \) | \( A = U \Sigma V^T \) | Dimensionality reduction, compression, least squares |
| **Cholesky Decomposition** | Symmetric positive-definite matrices | \( A = L L^T \) | Solving linear systems, optimization, statistics |


In [1]:
import numpy as np
import matplotlib.pyplot as plt

def cholesky_decomposition(A):
    """Computes the Cholesky decomposition of a positive-definite matrix A."""
    L = np.linalg.cholesky(A)
    return L

def eigen_decomposition(A):
    """Computes the eigen decomposition of a square matrix A."""
    eigenvalues, eigenvectors = np.linalg.eig(A)
    return eigenvalues, eigenvectors

def singular_value_decomposition(A):
    """Computes the Singular Value Decomposition (SVD) of matrix A."""
    U, S, Vt = np.linalg.svd(A)
    return U, S, Vt

# Example matrices
A_cholesky = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
A_eigen = np.array([[2, 1], [1, 2]])
A_svd = np.array([[3, 2, 2], [2, 3, -2]])

# Compute decompositions
L = cholesky_decomposition(A_cholesky)
eigenvalues, eigenvectors = eigen_decomposition(A_eigen)
U, S, Vt = singular_value_decomposition(A_svd)

# Display results
print("Cholesky Decomposition:\n", L)
print("\nEigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print("\nSVD U:\n", U)
print("Singular Values:\n", S)
print("SVD Vt:\n", Vt)


Cholesky Decomposition:
 [[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]

Eigenvalues:
 [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

SVD U:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Singular Values:
 [5. 3.]
SVD Vt:
 [[ 7.07106781e-01  7.07106781e-01  3.88578059e-16]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]



![SVD Decomposition](image1.png)


The given image illustrates the Singular Value Decomposition (SVD) of a **movie rating matrix**. It represents ratings given by three users (Ali, Beatrix, Chandra) to four movies (Star Wars, Blade Runner, Amelie, Delicatessen).

*image taken from the book mathematics for machine learning*
### **Step 1: Original Matrix Representation**
The original matrix \( A \) contains movie ratings:

$$[
A =
\begin{bmatrix}
5 & 4 & 1 \\
5 & 5 & 0 \\
0 & 0 & 5 \\
1 & 0 & 4
\end{bmatrix}
]$$

Each row corresponds to a movie, and each column corresponds to a user.

### **Step 2: SVD Factorization**
SVD decomposes the matrix \( A \) into three matrices:

$[
A = U \Sigma V^T
]$

where:

- $( U )$ (left singular vectors): Represents movie preferences in a transformed space.
- $( \Sigma )$ (singular values): Contains the importance (or strength) of each singular component.
- $( V^T )$ (right singular vectors): Represents user preferences in a transformed space.

#### **Matrix \( U \) (Left Singular Vectors)**
$$[
U =
\begin{bmatrix}
\color{red} -0.6710 & 0.0236 & 0.4647 & -0.5774 \\
\color{red} -0.7197 & 0.2054 & -0.4759 & 0.4619 \\
-0.0939 & \color{blue} -0.7705 & -0.5268 & -0.3464 \\
-0.1515 & \color{blue} -0.6030 & 0.5293 & -0.5774
\end{bmatrix}
]$$

- The **first two columns** (highlighted in red and blue) represent the most significant singular vectors, capturing most of the variation in the dataset.
- These vectors **represent a transformed basis for the movies** in terms of hidden factors (e.g., "sci-fi vs. drama" or "classic vs. modern").

#### **Matrix \( \Sigma \) (Singular Values)**
$$[
\Sigma =
\begin{bmatrix}
\color{red} 9.6438 & 0 & 0 & 0 \\
0 & \color{blue} 6.3639 & 0 & 0 \\
0 & 0 & 0.7056 & 0 \\
0 & 0 & 0 & 0
\end{bmatrix}
]$$

- The **largest singular value (9.6438, in red)** represents the most significant pattern in the ratings.
- The **second singular value (6.3639, in blue)** captures the next most important pattern.
- The last two singular values are much smaller, meaning they contribute less to the structure of the data.
- This suggests that the data can be **approximated well using just the first two singular vectors**, making SVD useful for dimensionality reduction.

#### **Matrix \( V^T \) (Right Singular Vectors)**
$$[
V^T =
\begin{bmatrix}
\color{green} -0.7367 & -0.6515 & -0.1811 \\
0.0852 & 0.1762 & \color{yellow} -0.9807 \\
0.6708 & -0.7379 & -0.0743
\end{bmatrix}
]$$

- The rows represent **users** in a transformed space.
- The first row (highlighted in green) represents the dominant user preference pattern.
- The second row (highlighted in yellow) captures a secondary pattern.
- This means that **users can also be grouped based on their rating behaviors**.

### **Interpretation: Finding Hidden Patterns**
- The SVD decomposition suggests that the **movie ratings can be explained using just two main underlying factors** instead of three.
- The singular values indicate that most of the data variation is captured in the first two components, meaning we could **compress this data** while still retaining most of the information.
- This technique is widely used in **recommendation systems**, where user preferences can be predicted based on hidden patterns in past ratings.

### **Key Takeaways**
- **\( U \)** represents transformed movies.
- $( \Sigma ) $  shows the strength of each pattern.
- **\( V^T \)** represents transformed users.
- The **largest singular values** highlight the most important structures in the data.
- **Dimensionality reduction**: Since smaller singular values contribute little, we can approximate the original matrix using only the first two singular values.

This SVD decomposition helps in understanding user preferences, reducing noise, and making better recommendations.

